export { default as makeOscillator } from './modules/oscillator'
export { default as makeGain } from './modules/gain'
export { default as makeOutput } from './modules/output'
export { default as makeAutoFilter } from './modules/autoFilter'
export { default as makeKompressor } from './modules/kompressor'
export { default as makeStereoPanner } from './modules/stereoPanner'
export { default as makeSignalDelay } from './modules/signalDelay'
export { default as makeConstantSource } from './modules/constant'
