export { default as FileControl } from './File'
export { default as TypeControl } from './Type'
export { default as ValueControl } from './Value'
export { default as ButtonControl } from './Button'
export { default as SwitchControl } from './Switch'
export { default as GraphControl } from './Graph'
export { default as TunerControl } from './OldTuner'